FROM docker.io/ubuntu:22.04

ENV PATH="/root/.cargo/bin:/usr/lib/llvm-15/bin:${PATH}"

# Ubuntu doesn't ship static zlib and zstd, because they adhere to the belief
# about "static linking considered harmful", so we have to build them
# ourselves.
RUN apt update \
    && apt install -y \
        build-essential \
        clang-15 \
        cmake \
        curl \
        lld-15 \
        ninja-build \
    && curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y \
    && rustup toolchain install stable --component rust-src \
    && rustup toolchain install nightly --component rust-src \
    && rm -rf /var/lib/apt/lists/*
