FROM docker.io/gentoo/stage3:musl-llvm

# Install llvm-libgcc, which is a drop-in replacement for libgcc_s runtime
# library. It's needed by Rust binaries provided by rustup[0][1].
#
# [0] https://github.com/rust-lang/rust/issues/119504
# [1] https://github.com/rust-lang/rustup/issues/2213#issuecomment-1888615413
RUN emerge --sync --quiet && \
    emerge \
        app-eselect/eselect-repository \
        dev-vcs/git && \
    eselect repository add vadorovsky git https://gitlab.com/vadorovsky/overlay && \
    emerge --sync --quiet && \
    emerge sys-libs/llvm-libgcc && \
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && \
    rustup toolchain install stable --component rust-src && \
    rustup toolchain install nightly --component rust-src && \
    rm -rf \
        /var/cache/binpkgs/* \
        /var/cache/distfiles/* \
        /var/tmp/portage/*

ENV PATH="/root/.cargo/bin:/usr/lib/llvm/18/bin:${PATH}"
