#!/bin/sh
set -eu

WRAPPER_DIR=$(dirname -- "$0")
export CARGO_BUILD_TARGET=x86_64-unknown-linux-musl
export CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_LINKER=$(realpath "${WRAPPER_DIR}/x86_64-linux-musl-clang")
export CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_RUNNER=$(realpath "${WRAPPER_DIR}/x86_64-linux-musl-run")

exec cargo "$@"
